### ISSUE TITLE
Which compilers does your version of fazang work with?

### ISSUE THREAD

**Issue by Beliavsky** [zoziha/fazang#1]
I want to add your version of fazang to my list at https://github.com/Beliavsky/Fortran-Tools . Could you say which compilers it works with -- I can put that in the description. Thanks.

**Comment by zoziha** [comment]
From the CI, gfortran for Windows/macOS/Linux is supported; since Meson doesn't support Windows-ifort much, I guess only ifort/ifx for macOS/Linux is supported.

PS. This repository is just carried because [the original repository](https://github.com/yizhang-yiz/fazang) can't pass compilation properly, so this repository may not be well developed afterward.

**Comment by Beliavsky** [comment]
Thanks -- I updated the fazang entry.
